spring:
  application:
    name: rocketmq-consume-demo

rocketmq:
  name-server: 10.119.6.210:9876

# properties used in application code
demo:
  rocketmq:
    topic: string-topic
    orderTopic: order-paid-topic
    msgExtTopic: message-ext-topic
    transTopic: spring-transaction-topic
    # another nameserver different global
    myNameServer: 10.119.6.210:9876