rocketmq:
  name-server: 10.119.6.210:9876;127.0.0.1:9876
  producer:
    group: my-group1
    sendMessageTimeout: 300000


# properties used in the application
demo:
  rocketmq:
    topic: string-topic
    orderTopic: order-paid-topic
    msgExtTopic: message-ext-topic
    transTopic: spring-transaction-topic
    extNameServer: 10.119.6.210:9876